
name: mkdocs
on:
  push:
    branches:
      - main
    paths:
       - "docs/**"
       - mkdocs.yaml
       - .github/workflows/mkdocs.yaml

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install mkdocs
        run: pip install -r requirements.txt
          
      - name: Build mkdocs
        run: mkdocs build

      - name: Upload mkdocs build artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: 'site'

  Publish:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Download mkdocs artifact
        uses: actions/download-artifact@v2
        with:
          name: site
          path: './site'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-skip-session-tagging: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-duration-seconds: 900
          role-session-name: GithubSession
          aws-region: eu-north-1

      - name: Upload site to S3 Bucket
        run: |
          cd site && aws s3 cp . ${{ secrets.MKDOCS_BUCKET }} --recursive
          
      - name: Invalidate Cloudfront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DIST_ID }} --path "/*"